packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: 5.8.2
  wireit: "^0.14.11"
  wrangler: "3.112.0"
  "@mantine/core": "7.17.1"
  "@mantine/hooks": "7.17.1"
  "@mantine/vanilla-extract": "7.17.1"
  "@mantine/modals": "7.17.1"
  "@mantine/notifications": "7.17.1"
  "@mantine/colors-generator": "7.17.1"
  "@types/node": 20.8.3

onlyBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd
