name: Report an issue
description: Use this template to report issues with LikeC4. To ask questions use GitHub discussions instead
body:
  - type: checkboxes
    id: dependencies
    attributes:
      label: Dependencies check up
      description: Before submitting an issue please make sure that you use latest version of LikeC4.
      options:
        - label: I have verified that I use latest version of LikeC4
          required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - "LikeC4 Language"
        - "LikeC4 CLI"
        - "VSCode extension"
        - "Other, I will specify in the description"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: |
        A clear and concise description of what the bug is.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: If possible, include a link to shared playground with example
      description: Create new blank playground https://playground.likec4.dev/, add your example and share the link here
